version: '3.8'

services:
  django:
    build:
      context: ./Backend
    ports:
      - "8000:8000"

  react:
    build:
      context: ./vapi-web-test
    ports:
      - "9000:9000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
