name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust the Python version as needed

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker compose --build
      
      - name: Tagging
        run: |
          docker tag backend-django:latest 192.168.2.17:6000/remote-vapi-umer-backend:latest
          docker tag backend-react:latest 192.168.2.17:6000/remote-vapi-umer-frontend:latest

      - name: Push
        run: |
          docker push 192.168.2.17:6000/remote-vapi-umer-backend:latest
          docker push 192.168.2.17:6000/remote-vapi-umer-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 192.168.2.17
          username: umer
          password: umer123
          port: 22
          script: |
            docker pull 192.168.2.17:6000/remote-vapi-umer-backend:latest
            docker pull 192.168.2.17:6000/remote-vapi-umer-frontend:latest
            docker-compose up

