name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Configure Docker for insecure registry
        run: |
          echo '{"insecure-registries" : ["116.58.60.115:6000"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      
      - name: Build Docker images
        run: |
          docker build -t backend-django:latest ./Backend
          docker build -t backend-react:latest ./vapi-web-test
      
      - name: Tagging
        run: |
          docker tag backend-django:latest 116.58.60.115:6000/remote-vapi-umer-backend:latest
          docker tag backend-react:latest 116.58.60.115:6000/remote-vapi-umer-frontend:latest
      
      - name: Log in to Docker registry
        run: echo "umer123" | docker login 116.58.60.115:6000 -u umer --password-stdin
      
      - name: Push
        run: |
          docker push 116.58.60.115:6000/remote-vapi-umer-backend:latest
          docker push 116.58.60.115:6000/remote-vapi-umer-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 116.58.60.115
          username: umer
          password: umer123
          script: |
            docker pull 116.58.60.115:6000/remote-vapi-umer-backend:latest
            docker pull 116.58.60.115:6000/remote-vapi-umer-frontend:latest
            docker-compose -f /mnt/myhdd/production/doctorgpt/docker-compose.yml up -d